Exit and return an exit status if any `exec` subcommand fails.
This commit relates to this issue:

https://github.com/kamataryo/monorepo/issues/24#issuecomment-426838432

It should make failures more obvious.

This commit also updates `.rubocop.yml` as Rubocop updates caused the
deprecation error:
`
Error: The \`Style/TrailingCommaInLiteral\` cop no longer exists. Please use
\`Style/TrailingCommaInArrayLiteral\` and/or
\`Style/TrailingCommaInHashLiteral\` instead. (obsolete configuration found in
.rubocop.yml, please update it)
`

Rubocop also asked to use `$CHILD_STATUS` instead of `$?` which means
`require`ing `english` from stdlib. (Sorry, it's a bit obnoxious to
non-English speakers to have a gem called english required.)

If there's too much going on here for one commit, I'm happy to spit it.